import { Fighter } from './fighter';

export const CAPCOM_CAST: Fighter[] = [
	{ id: 27, name: "Akuma" },
	{ id: 28, name: "Amingo" },
	{ id: 29, name: "Anakaris" },
	{ id: 30, name: "B.B. Hood" },
	{ id: 31, name: "Cammy White" },
	{ id: 32, name: "Captain Commando" },
	{ id: 33, name: "Charlie Nash" },
	{ id: 34, name: "Chun-Li" },
	{ id: 35, name: "Dan Hibiki" },
	{ id: 36, name: "Dhalsim" },
	{ id: 37, name: "Felicia" },
	{ id: 38, name: "Guile" },
	{ id: 39, name: "Hayato Kanzaki" },
	{ id: 40, name: "Jill Valentine" },
	{ id: 41, name: "Jin Saotone" },
	{ id: 42, name: "Ken Masters" },
	{ id: 43, name: "M. Bison" },
	{ id: 44, name: "Mega Man" },
	{ id: 45, name: "Morrigan Aensland" },
	{ id: 46, name: "Roll" },
	{ id: 47, name: "Ruby Heart" },
	{ id: 48, name: "Ryu" },
	{ id: 49, name: "Sakura Kasugano" },
	{ id: 50, name: "Servbot" },
	{ id: 51, name: "SonSon" },
	{ id: 52, name: "Strider Hiryu" },
	{ id: 53, name: "Tron Bonne" },
	{ id: 54, name: "Zangief" },
];
