import { Fighter } from "./fighter";

export const FIGHTER_CAST: Fighter[] = [
	{ id: 0, name: "Blackheart" },
	{ id: 1, name: "Cable" },
	{ id: 2, name: "Captain America" },
	{ id: 3, name: "Colossus" },
	{ id: 4, name: "Cyclops" },
	{ id: 5, name: "Doctor Doom" },
	{ id: 6, name: "Gambit" },
	{ id: 7, name: "Hulk" },
	{ id: 8, name: "Iceman" },
	{ id: 9, name: "Iron Man" },
	{ id: 10, name: "Juggernaut" },
	{ id: 11, name: "Magneto" },
	{ id: 12, name: "Marrow" },
	{ id: 13, name: "Omega Red" },
	{ id: 14, name: "Psylocke" },
	{ id: 15, name: "Rogue" },
	{ id: 16, name: "Sabretooth" },
	{ id: 17, name: "Sentinel" },
	{ id: 18, name: "Shuma-Gorath" },
	{ id: 19, name: "Silver Samurai" },
	{ id: 20, name: "Spider-Man" },
	{ id: 21, name: "Spiral" },
	{ id: 22, name: "Storm" },
	{ id: 23, name: "Thanos" },
	{ id: 24, name: "Venom" },
	{ id: 25, name: "War Machine" },
	{ id: 26, name: "Wolverine" },
];

/*
export const CAPCOM_CAST: Fighter[] = [
	{ id: 27, name: "Akuma" },
	{ id: 28, name: "Amingo" },
	{ id: 29, name: "Anakaris" },
	{ id: 30, name: "B.B. Hood" },
	{ id: 31, name: "Cammy White" },
	{ id: 32, name: "Captain Commando" },
	{ id: 33, name: "Charlie Nash" },
	{ id: 34, name: "Chun-Li" },
	{ id: 35, name: "Dan Hibiki" },
	{ id: 36, name: "Dhalsim" },
	{ id: 37, name: "Felicia" },
	{ id: 38, name: "Guile" },
	{ id: 39, name: "Hayato Kanzaki" },
	{ id: 40, name: "Jill Valentine" },
	{ id: 41, name: "Jin Saotone" },
	{ id: 42, name: "Ken Masters" },
	{ id: 43, name: "M. Bison" },
	{ id: 44, name: "Mega Man" },
	{ id: 45, name: "Morrigan Aensland" },
	{ id: 46, name: "Roll" },
	{ id: 47, name: "Ruby Heart" },
	{ id: 48, name: "Ryu" },
	{ id: 49, name: "Sakura Kasugano" },
	{ id: 50, name: "Servbot" },
	{ id: 51, name: "SonSon" },
	{ id: 52, name: "Strider Hiryu" },
	{ id: 53, name: "Tron Bonne" },
	{ id: 54, name: "Zangief" },
];
*/