import { Fighter } from "./fighter";

export const FIGHTER_CAST: Fighter[] = [
	{ id: 0, name: "Blackheart" },
	{ id: 1, name: "Cable" },
	{ id: 2, name: "Captain America" },
	{ id: 3, name: "Colossus" },
	{ id: 4, name: "Cyclops" },
	{ id: 5, name: "Doctor Doom" },
	{ id: 6, name: "Gambit" },
	{ id: 7, name: "Hulk" },
	{ id: 8, name: "Iceman" },
	{ id: 9, name: "Iron Man" },
	{ id: 10, name: "Juggernaut" },
	{ id: 11, name: "Magneto" },
	{ id: 12, name: "Marrow" },
	{ id: 13, name: "Omega Red" },
	{ id: 14, name: "Psylocke" },
	{ id: 15, name: "Rogue" },
	{ id: 16, name: "Sabretooth" },
	{ id: 17, name: "Sentinel" },
	{ id: 18, name: "Shuma-Gorath" },
	{ id: 19, name: "Silver Samurai" },
	{ id: 20, name: "Spider-Man" },
	{ id: 21, name: "Spiral" },
	{ id: 22, name: "Storm" },
	{ id: 23, name: "Thanos" },
	{ id: 24, name: "Venom" },
	{ id: 25, name: "War Machine" },
	{ id: 26, name: "Wolverine" },
];

/*
export const CAPCOM_CAST: Fighter[] = [
	{ id: 0, name: "Akuma" },
	{ id: 1, name: "Amingo" },
	{ id: 2, name: "Anakaris" },
	{ id: 3, name: "B.B. Hood" },
	{ id: 4, name: "Cammy White" },
	{ id: 5, name: "Captain Commando" },
	{ id: 6, name: "Charlie Nash" },
	{ id: 7, name: "Chun-Li" },
	{ id: 8, name: "Dan Hibiki" },
	{ id: 9, name: "Dhalsim" },
	{ id: 10, name: "Felicia" },
	{ id: 11, name: "Gulie" },
	{ id: 12, name: "Hayato Kanzaki" },
	{ id: 13, name: "Jill Valentine" },
	{ id: 14, name: "Jin Saotone" },
	{ id: 15, name: "Ken Masters" },
	{ id: 16, name: "M. Bison" },
	{ id: 17, name: "Mega Man" },
	{ id: 18, name: "Morrigan Aensland" },
	{ id: 19, name: "Roll" },
	{ id: 20, name: "Ruby Heart " },
	{ id: 21, name: "Ryu" },
	{ id: 22, name: "Sakura Kasugano" },
	{ id: 23, name: "Servbot" },
	{ id: 24, name: "SonSon" },
	{ id: 25, name: "Strider Hiryu" },
	{ id: 26, name: "Tron Bonne" },
	{ id: 27, name: "Zangief" },
];
*/