import { Fighter } from "./fighter";

export const MARVEL_CAST: Fighter[] = [
	{ id: 0, name: "Blackheart" },
	{ id: 1, name: "Cable" },
	{ id: 2, name: "Captain America" },
	{ id: 3, name: "Colossus" },
	{ id: 4, name: "Cyclops" },
	{ id: 5, name: "Doctor Doom" },
	{ id: 6, name: "Gambit" },
	{ id: 7, name: "Hulk" },
	{ id: 8, name: "Iceman" },
	{ id: 9, name: "Iron Man" },
	{ id: 10, name: "Juggernaut" },
	{ id: 11, name: "Magneto" },
	{ id: 12, name: "Marrow" },
	{ id: 13, name: "Omega Red" },
	{ id: 14, name: "Psylocke" },
	{ id: 15, name: "Rogue" },
	{ id: 16, name: "Sabretooth" },
	{ id: 17, name: "Sentinel" },
	{ id: 18, name: "Shuma-Gorath" },
	{ id: 19, name: "Silver Samurai" },
	{ id: 20, name: "Spider-Man" },
	{ id: 21, name: "Spiral" },
	{ id: 22, name: "Storm" },
	{ id: 23, name: "Thanos" },
	{ id: 24, name: "Venom" },
	{ id: 25, name: "War Machine" },
	{ id: 26, name: "Wolverine" },
];